name: asthma
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.36
  audio_video_progress_bar: ^2.0.1
  geolocator: ^10.1.0
  http: ^1.1.2
  url_launcher: ^6.2.1
  flutter_bloc: ^8.1.3
  pinput: ^3.0.1
  screenshot: ^2.1.0
  image_gallery_saver: ^2.0.3
  supabase_flutter: ^1.10.25
  flutter_dotenv: ^5.1.0
  rxdart: ^0.27.7
  barcode_widget: ^2.0.4
  image_picker: ^1.0.4
  flutter_advanced_drawer: ^1.3.5
  geocoding: ^2.1.1
  adaptive_theme: ^3.4.1
  lottie: ^2.7.0
  flutter_localizations:
    sdk: flutter
  intl: any
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - lib/assets/images/
    - assets/
    - lib/assets/
    - lib/assets/audio/beach.mp3
    - lib/assets/audio/AAA.mp3
    - lib/assets/audio/Breathing_Exercise.mp3
    - .env
